# Generated by Django 4.1.7 on 2024-03-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='deliveryboys',
            fields=[
                ('email', models.EmailField(default=0, max_length=254, unique=True)),
                ('d_username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('d_name', models.CharField(max_length=50)),
                ('d_phone', models.PositiveBigIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('password', models.CharField(default=0, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50, unique=True)),
                ('dish_code', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
                ('types', models.CharField(choices=[('vegbiryani', 'Veg Biryani'), ('nonvegbiryani', 'Non-Veg Biryani'), ('nonvegstarter', 'Non-Veg Starter'), ('vegstarter', 'Veg Starter')], max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='dishes/images/')),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('delivery_boy_assigned', models.BooleanField(default=False)),
                ('delivery_boy_pickedpackage', models.BooleanField(default=False)),
                ('order_delivered', models.BooleanField(default=False)),
                ('dish_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_dish_code', to='adminapp.dishes')),
                ('dish_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_dish_name', to='adminapp.dishes')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='deliverymapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=0, max_length=300)),
                ('phone', models.BigIntegerField()),
                ('d_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverymapping_d_username', to='adminapp.deliveryboys')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverymapping_username', to='sapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('dish_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.dishes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.userprofile')),
            ],
        ),
    ]
