# Generated by Django 4.1.7 on 2024-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_of_order',
            field=models.DateField(),
        ),
    ]
