# Generated by Django 5.0.3 on 2024-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_cartprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartprice',
            name='finalprice',
            field=models.IntegerField(default=0),
        ),
    ]
