# Generated by Django 5.0.3 on 2024-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_cartprice_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartprice',
            name='finalprice',
            field=models.FloatField(default=0.0),
        ),
    ]
