# Generated by Django 5.0.3 on 2024-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_cartprice_finalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='finalpricee',
            field=models.FloatField(default=0.0),
        ),
    ]
