# Generated by Django 5.0.3 on 2024-04-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_orders_finalpricee'),
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverymappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=0, max_length=300)),
                ('phone', models.BigIntegerField()),
                ('d_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverymapping_d_usernames', to='adminapp.deliveryboys')),
                ('ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to='adminapp.orders')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverymapping_usernames', to='sapp.userprofile')),
            ],
        ),
    ]
