# Generated by Django 5.0.3 on 2024-04-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_deliverymappings'),
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderverif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifcode', models.BigIntegerField()),
                ('orderse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.orders')),
                ('useres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.userprofile')),
            ],
        ),
    ]
