# Generated by Django 5.0.3 on 2024-04-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_orderverif'),
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverymappingss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=0, max_length=300)),
                ('phone', models.BigIntegerField()),
                ('d_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverymapping_d_usernamese', to='adminapp.deliveryboys')),
                ('ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_usere', to='adminapp.orders')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverymapping_usernamese', to='sapp.userprofile')),
            ],
        ),
    ]
