# Generated by Django 5.0.3 on 2024-04-09 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_review'),
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_of_order', models.DateField()),
                ('finalpricee', models.FloatField(default=0.0)),
                ('delivery_boy_assigned', models.BooleanField(default=False)),
                ('delivery_boy_pickedpackage', models.BooleanField(default=False)),
                ('order_delivered', models.BooleanField(default=False)),
                ('dish_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_dish_codee', to='adminapp.dishes')),
                ('dish_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_dish_namee', to='adminapp.dishes')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.userprofile')),
            ],
        ),
    ]
