# Generated by Django 5.0.3 on 2024-04-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.order'),
        ),
    ]
