# Generated by Django 5.0.3 on 2024-04-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_review_ords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymappingss',
            name='ord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_usere', to='adminapp.order'),
        ),
    ]
